// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// BLOGPOSTS_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IBLOGPOSTS_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the BLOGPOSTS_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> BLOGPOSTS_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedBLOGPOSTS_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedBLOGPOSTS_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedMenuSection_MenuMenuControl property.
        /// </summary>
		Controls.MenuItemData SelectedMenuSection_MenuMenuControl { get; set; }
        /// <summary>
        /// Gets/Sets the CurrentABOUTUS_InfoHtmlControl property.
        /// </summary>
		string CurrentABOUTUS_InfoHtmlControl { get; set; }
        
        /// <summary>
        /// Gets the RefreshBLOGPOSTS_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshBLOGPOSTS_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetBLOGPOSTS_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand GetBLOGPOSTS_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechABOUTUS_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechABOUTUS_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareABOUTUS_InfoHtmlControlCommand command.
        /// </summary>
		ICommand ShareABOUTUS_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartABOUTUS_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartABOUTUS_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
