// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// BLOGPOSTS_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IBLOGPOSTS_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaBLOGPOSTS_Detail0 property.
        /// </summary>
		bool HasNextpanoramaBLOGPOSTS_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaBLOGPOSTS_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaBLOGPOSTS_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechBLOGPOSTS_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechBLOGPOSTS_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareBLOGPOSTS_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareBLOGPOSTS_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartBLOGPOSTS_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartBLOGPOSTS_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceBLOGPOSTS_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceBLOGPOSTS_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaBLOGPOSTS_Detail0 command.
        /// </summary>
		ICommand NextpanoramaBLOGPOSTS_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaBLOGPOSTS_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaBLOGPOSTS_Detail0 { get; }

	}
}
